//! `concir-instrument` v2: rewrite a free std-only Rust program onto
//! instrumented `cir_trace::sync` wrapper types.
//!
//! Unlike the v1 call-site annotator (which inserts `cir_trace::ev` before each
//! operation and therefore cannot see guard-drop unlocks), v2 replaces the
//! `std::sync::{Mutex, Condvar}` names with wrappers whose `lock`/`Guard::drop`,
//! `wait`, `notify_*` emit operation-bound `(tag, op, resource, sid)` events.
//! Resource names are derived from the binding the constructor is assigned to,
//! so `Arc::clone`d handles share one name. Sids are generated by
//! `(resource, op, occurrence)` at runtime.
//!
//! The transform is intentionally conservative: it handles `Mutex` and
//! `Condvar` (the primitives of the lock-order/condvar families) and reports
//! everything it cannot cover (RwLock, barriers, atomics, macro bodies,
//! generics) as a limitation instead of silently dropping it.

use std::collections::BTreeMap;

use syn::spanned::Spanned;
use syn::visit::Visit;
use syn::{Expr, ExprCall, File, Pat, Stmt};

/// Runtime emitted next to the instrumented source as `cir_trace.rs`.
pub const RUNTIME: &str = r#"// Generated cir_trace runtime v2 (std only, wrapper types).
#![allow(dead_code)]
use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::OnceLock;

static EVENTS: OnceLock<std::sync::Mutex<Vec<(String, String, String, String)>>> = OnceLock::new();
static MAIN: OnceLock<std::thread::ThreadId> = OnceLock::new();
static NEXT_TAG: AtomicU64 = AtomicU64::new(1);
static SIDS: OnceLock<std::sync::Mutex<HashMap<String, u64>>> = OnceLock::new();

thread_local! {
    static TAG: std::cell::RefCell<Option<String>> = const { std::cell::RefCell::new(None) };
}

/// Pin the main thread's tag to `t0` before any worker can run.
pub fn init() {
    let _ = MAIN.set(std::thread::current().id());
    let _ = EVENTS.get_or_init(|| std::sync::Mutex::new(Vec::new()));
}

/// Thread tag: the eager spawn-order tag when set, `t0` for main, and a lazy
/// fallback for threads created without the helper.
pub fn tag() -> String {
    if let Some(t) = TAG.with(|t| t.borrow().clone()) {
        return t;
    }
    let tid = std::thread::current().id();
    let main = *MAIN.get_or_init(|| tid);
    if tid == main {
        return "t0".to_string();
    }
    let n = NEXT_TAG.fetch_add(1, Ordering::SeqCst);
    let name = format!("t{}", n);
    TAG.with(|t| *t.borrow_mut() = Some(name.clone()));
    name
}

fn next_sid(resource: &str, op: &str) -> String {
    let key = format!("{resource}:{op}");
    let sids = SIDS.get_or_init(|| std::sync::Mutex::new(HashMap::new()));
    let mut map = sids.lock().unwrap();
    let c = map.entry(key.clone()).or_insert(0);
    *c += 1;
    format!("{key}#{c}")
}

pub fn record(op: &str, resource: &str) {
    let sid = next_sid(resource, op);
    let events = EVENTS.get_or_init(|| std::sync::Mutex::new(Vec::new()));
    events
        .lock()
        .unwrap()
        .push((tag(), op.to_string(), resource.to_string(), sid));
}

/// Spawn a worker and record it; the child's completion is witnessed by the
/// program finishing (a finished trace implies `main` returned).
pub fn spawn<F>(name: &'static str, f: F) -> std::thread::JoinHandle<()>
where
    F: FnOnce() + Send + 'static,
{
    record("spawn", name);
    let n = NEXT_TAG.fetch_add(1, Ordering::SeqCst);
    let tag = format!("t{}", n);
    std::thread::spawn(move || {
        TAG.with(|t| *t.borrow_mut() = Some(tag));
        f()
    })
}

pub fn finish() {
    if let Ok(path) = std::env::var("CIR_TRACE_OUT") {
        let events = EVENTS.get_or_init(|| std::sync::Mutex::new(Vec::new()));
        let guard = events.lock().unwrap();
        let mut out = String::new();
        for (t, op, r, s) in guard.iter() {
            out.push_str(&format!(
                "{{\"t\":\"{}\",\"sid\":\"{}\",\"op\":\"{}\",\"r\":\"{}\"}}\n",
                t, s, op, r
            ));
        }
        let _ = std::fs::write(path, out);
    }
}

pub mod sync {
    use super::record;
    use std::ops::{Deref, DerefMut};
    use std::sync::{Condvar as StdCondvar, LockResult, Mutex as StdMutex};

    pub struct Mutex<T> {
        inner: StdMutex<T>,
        name: &'static str,
    }

    pub struct Guard<'a, T> {
        inner: Option<std::sync::MutexGuard<'a, T>>,
        name: &'static str,
        armed: bool,
    }

    impl<T> Mutex<T> {
        pub fn new(value: T) -> Self {
            Self::new_named("mutex", value)
        }
        pub fn new_named(name: &'static str, value: T) -> Self {
            Mutex { inner: StdMutex::new(value), name }
        }
        pub fn lock(&self) -> LockResult<Guard<'_, T>> {
            match self.inner.lock() {
                Ok(g) => {
                    record("mutex_lock", self.name);
                    Ok(Guard { inner: Some(g), name: self.name, armed: true })
                }
                Err(e) => {
                    let g: std::sync::MutexGuard<'_, T> = e.into_inner();
                    record("mutex_lock", self.name);
                    Ok(Guard { inner: Some(g), name: self.name, armed: true })
                }
            }
        }
    }

    impl<'a, T> Deref for Guard<'a, T> {
        type Target = T;
        fn deref(&self) -> &T {
            self.inner.as_ref().unwrap()
        }
    }

    impl<'a, T> DerefMut for Guard<'a, T> {
        fn deref_mut(&mut self) -> &mut T {
            self.inner.as_mut().unwrap()
        }
    }

    impl<'a, T> Drop for Guard<'a, T> {
        fn drop(&mut self) {
            if self.armed {
                record("mutex_unlock", self.name);
            }
        }
    }

    pub struct Condvar {
        inner: StdCondvar,
        name: &'static str,
    }

    impl Default for Condvar {
        fn default() -> Self {
            Self::new()
        }
    }

    impl Condvar {
        pub fn new() -> Self {
            Self::new_named("condvar")
        }
        pub fn new_named(name: &'static str) -> Self {
            Condvar { inner: StdCondvar::new(), name }
        }
        pub fn wait<'a, T>(&self, mut guard: Guard<'a, T>) -> LockResult<Guard<'a, T>> {
            let name = guard.name;
            guard.armed = false;
            let inner: std::sync::MutexGuard<'a, T> =
                guard.inner.take().expect("condvar guard consumed twice");
            record("mutex_unlock", name);
            let result = self.inner.wait(inner);
            record("mutex_lock", name);
            record("condvar_wait", self.name);
            match result {
                Ok(g) => Ok(Guard { inner: Some(g), name, armed: true }),
                Err(_) => Ok(Guard { inner: None, name, armed: false }),
            }
        }
        pub fn notify_one(&self) {
            record("condvar_notify", self.name);
            self.inner.notify_one();
        }
        pub fn notify_all(&self) {
            record("condvar_notify_all", self.name);
            self.inner.notify_all();
        }
    }

}
"#;

#[derive(Debug, Clone, serde::Serialize)]
pub struct Resource {
    pub name: String,
    pub kind: String,
}

#[derive(Debug, Clone)]
pub struct Wrapped {
    pub annotated: String,
    pub runtime: String,
    pub resources: Vec<Resource>,
    pub limitations: Vec<String>,
}

struct Edit {
    start: usize,
    end: usize,
    text: String,
}

fn line_starts(src: &str) -> Vec<usize> {
    let mut starts = vec![0usize];
    for (i, b) in src.bytes().enumerate() {
        if b == b'\n' {
            starts.push(i + 1);
        }
    }
    starts
}

fn lc_offset(starts: &[usize], lc: proc_macro2::LineColumn) -> usize {
    let line = lc.line.saturating_sub(1).min(starts.len().saturating_sub(1));
    starts[line] + lc.column
}

fn leading_header_len(src: &str) -> usize {
    let mut offset = 0;
    for line in src.split_inclusive('\n') {
        let trimmed = line.trim_start();
        if trimmed.starts_with("//!") || trimmed.starts_with("#![") || trimmed.trim().is_empty() {
            offset += line.len();
        } else {
            break;
        }
    }
    offset
}

fn ctor_kind(path: &syn::Path) -> Option<&'static str> {
    let segs: Vec<String> = path.segments.iter().map(|s| s.ident.to_string()).collect();
    if segs.last().map(String::as_str) != Some("new") {
        return None;
    }
    match segs.get(segs.len().wrapping_sub(2)).map(String::as_str) {
        Some("Mutex") => Some("Mutex"),
        Some("Condvar") => Some("Condvar"),
        _ => None,
    }
}

struct CtorHit {
    new_start: usize,
    new_end: usize,
    open_brace: usize,
    empty_args: bool,
    kind: &'static str,
}

struct SpawnHit {
    callee_start: usize,
    callee_end: usize,
    open_brace: usize,
}

struct CtorCollector {
    starts: Vec<usize>,
    hits: Vec<CtorHit>,
    spawns: Vec<SpawnHit>,
}

fn is_thread_spawn(path: &syn::Path) -> bool {
    let segs: Vec<String> = path.segments.iter().map(|s| s.ident.to_string()).collect();
    segs.last().map(String::as_str) == Some("spawn")
        && segs.iter().any(|s| s == "thread")
}

impl<'ast> Visit<'ast> for CtorCollector {
    fn visit_expr_call(&mut self, node: &'ast ExprCall) {
        if let Expr::Path(p) = &*node.func {
            if is_thread_spawn(&p.path) {
                let open = lc_offset(&self.starts, node.paren_token.span.open().start()) + 1;
                self.spawns.push(SpawnHit {
                    callee_start: lc_offset(&self.starts, p.path.span().start()),
                    callee_end: lc_offset(&self.starts, p.path.span().end()),
                    open_brace: open,
                });
            } else if let Some(kind) = ctor_kind(&p.path) {
                let ident = p.path.segments.last().expect("callee path").ident.clone();
                let open = lc_offset(&self.starts, node.paren_token.span.open().start()) + 1;
                self.hits.push(CtorHit {
                    new_start: lc_offset(&self.starts, ident.span().start()),
                    new_end: lc_offset(&self.starts, ident.span().end()),
                    open_brace: open,
                    empty_args: node.args.is_empty(),
                    kind,
                });
            }
        }
        syn::visit::visit_expr_call(self, node);
    }
}

struct Namer {
    starts: Vec<usize>,
    edits: Vec<Edit>,
    resources: Vec<Resource>,
}

impl Namer {
    fn name_constructors(&mut self, local: &syn::Local) {
        let Some(init) = &local.init else { return };
        let mut collector = CtorCollector {
            starts: self.starts.clone(),
            hits: Vec::new(),
            spawns: Vec::new(),
        };
        collector.visit_expr(&init.expr);
        if collector.hits.is_empty() && collector.spawns.is_empty() {
            return;
        }
        let base = match &local.pat {
            Pat::Ident(i) => i.ident.to_string(),
            _ => "res".to_string(),
        };
        let spawn_total = collector.spawns.len();
        for (index, hit) in collector.spawns.into_iter().enumerate() {
            let name = if base != "res" && spawn_total == 1 {
                base.clone()
            } else if base != "res" {
                format!("{base}_{index}")
            } else {
                format!("spawn{index}")
            };
            self.edits.push(Edit {
                start: hit.callee_start,
                end: hit.callee_end,
                text: "cir_trace::spawn".to_string(),
            });
            self.edits.push(Edit {
                start: hit.open_brace,
                end: hit.open_brace,
                text: format!("\"{name}\", "),
            });
            self.resources.push(Resource { name, kind: "Spawn".to_string() });
        }
        let mut counters: BTreeMap<&'static str, usize> = BTreeMap::new();
        for hit in collector.hits {
            let k = counters.entry(hit.kind).or_insert(0);
            let name = format!("{}_{}{}", base, hit.kind.to_lowercase(), *k);
            *k += 1;
            let text = if hit.empty_args {
                format!("\"{name}\"")
            } else {
                format!("\"{name}\", ")
            };
            self.edits.push(Edit {
                start: hit.new_start,
                end: hit.new_end,
                text: "new_named".to_string(),
            });
            self.edits.push(Edit { start: hit.open_brace, end: hit.open_brace, text });
            self.resources.push(Resource { name, kind: hit.kind.to_string() });
        }
    }
}

impl<'ast> Visit<'ast> for Namer {
    fn visit_stmt(&mut self, node: &'ast Stmt) {
        if let Stmt::Local(local) = node {
            self.name_constructors(local);
        }
        syn::visit::visit_stmt(self, node);
    }
}

struct MainFinder {
    starts: Vec<usize>,
    open: Option<usize>,
    close: Option<usize>,
}

impl<'ast> Visit<'ast> for MainFinder {
    fn visit_item_fn(&mut self, node: &'ast syn::ItemFn) {
        if node.sig.ident == "main" {
            let open = lc_offset(&self.starts, node.block.brace_token.span.open().start());
            let close = lc_offset(&self.starts, node.block.brace_token.span.close().start());
            self.open = Some(open + 1);
            self.close = Some(close);
        }
        syn::visit::visit_item_fn(self, node);
    }
}

/// Remove `Mutex`/`Condvar` from `use std::sync::{...}` and simple uses so the
/// names can be provided by `cir_trace::sync`.
fn rewrite_imports(src: &str) -> String {
    let mut out = src.to_string();
    for name in ["Mutex", "Condvar"] {
        out = out.replace(&format!("use std::sync::{name};"), "");
    }
    let mut result = String::new();
    let mut rest = out.as_str();
    while let Some(i) = rest.find("use std::sync::{") {
        let (before, from) = rest.split_at(i);
        result.push_str(before);
        let after = &from["use std::sync::{".len()..];
        if let Some(j) = after.find('}') {
            let inner = &after[..j];
            let rest2 = &after[j + 1..];
            let semi = rest2.find(';').map(|k| k + 1).unwrap_or(0);
            let items: Vec<&str> = inner
                .split(',')
                .map(str::trim)
                .filter(|s| !s.is_empty() && *s != "Mutex" && *s != "Condvar")
                .collect();
            if !items.is_empty() {
                result.push_str(&format!("use std::sync::{{{}}};", items.join(", ")));
            }
            rest = &rest2[semi..];
        } else {
            result.push_str(from);
            rest = "";
        }
    }
    result.push_str(rest);
    result
        .replace("std::sync::Mutex", "cir_trace::sync::Mutex")
        .replace("std::sync::Condvar", "cir_trace::sync::Condvar")
}

fn limitations_of(src: &str) -> Vec<String> {
    let mut out = Vec::new();
    for (token, note) in [
        ("RwLock", "RwLock is not instrumented"),
        ("Barrier", "Barrier is not instrumented"),
        ("Once", "Once is not instrumented"),
        ("atomic", "atomics are not instrumented (no value events)"),
        ("thread::scope", "thread::scope tags are runtime-derived, scope event absent"),
        ("async ", "async/await is not supported"),
        ("select!", "select is not supported"),
    ] {
        if src.contains(token) {
            out.push(note.to_string());
        }
    }
    out
}

pub fn wrap(src: &str) -> Result<Wrapped, String> {
    let file: File = syn::parse_file(src).map_err(|e| format!("parse error: {e}"))?;
    let starts = line_starts(src);

    let mut namer = Namer { starts: starts.clone(), edits: Vec::new(), resources: Vec::new() };
    namer.visit_file(&file);

    let mut finder = MainFinder { starts: starts.clone(), open: None, close: None };
    finder.visit_file(&file);
    let (Some(main_open), Some(main_close)) = (finder.open, finder.close) else {
        return Err("no `fn main` found".to_string());
    };

    // Insert init() at the top of main and finish() before its closing brace.
    let mut edits = namer.edits;
    edits.push(Edit {
        start: main_open,
        end: main_open,
        text: " cir_trace::init();".to_string(),
    });
    edits.push(Edit {
        start: main_close,
        end: main_close,
        text: " cir_trace::finish();".to_string(),
    });

    // Header: module declaration + imports.
    let header = if src.contains("Mutex") || src.contains("Condvar") {
        "mod cir_trace;\nuse cir_trace::sync::{Mutex, Condvar};\n"
    } else {
        "mod cir_trace;\n"
    };
    edits.push(Edit { start: leading_header_len(src), end: leading_header_len(src), text: header.to_string() });

    let mut annotated = src.to_string();
    edits.sort_by(|a, b| b.start.cmp(&a.start).then(b.end.cmp(&a.end)));
    for edit in edits {
        annotated.replace_range(edit.start..edit.end, &edit.text);
    }
    // Then rewrite imports on the annotated text (offset-independent).
    annotated = rewrite_imports(&annotated);

    Ok(Wrapped {
        annotated,
        runtime: RUNTIME.to_string(),
        resources: namer.resources,
        limitations: limitations_of(src),
    })
}
